<a href="https://colab.research.google.com/github/Guilhermeslsand/Python/blob/main/Aula_Pratica_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np
import math
import matplotlib.pyplot as plt


In [9]:
ordem = int(input("Ordem do do sistema: "))

Ordem do do sistema: 3


In [10]:
A = np.zeros([ordem,ordem], dtype = 'float')

In [11]:
for i in range(0,ordem):
  for j in range(0,ordem):
    A[i][j] = int(input(f'Elemento da possição ({i+1},{j+1}) da matriz A:'))

Elemento da possição (1,1) da matriz A:1
Elemento da possição (1,2) da matriz A:2
Elemento da possição (1,3) da matriz A:-1
Elemento da possição (2,1) da matriz A:-1
Elemento da possição (2,2) da matriz A:2
Elemento da possição (2,3) da matriz A:0
Elemento da possição (3,1) da matriz A:2
Elemento da possição (3,2) da matriz A:1
Elemento da possição (3,3) da matriz A:-1


In [84]:
print(A)

[[ 1.  2. -1.]
 [-1.  2.  0.]
 [ 2.  1. -1.]]


In [115]:
def elimina_gauss_piv(A,B):
  Ac= np.copy(A)
  Bc = np.copy(B)

  for i in range(0,len(Ac)-1):
    pivo = Ac[i,i]
    z = i+1
    achou = 0
    linha = i
    while  z < len(Ac):
      if abs(Ac[z,i]) > abs(pivo):
        pivo = Ac[z,i]
        linha = z
        achou = 1
      z = z + 1
    if achou == 1:
      Aux = np.copy(Ac)
      Ac[i,:] = np.copy(Ac[linha,:])
      Ac[linha,:] = np.copy(Aux[i,:])
      Aux = np.copy(Bc)
      Bc[i] = np.copy(Bc[linha])
      Bc[linha] = np.copy(Aux[i])

    for j in (i+1,len(A)-1):
      cofator = (-1)*Ac[j,i]/Ac[i,i]
      Ac[j,:] = Ac[i,:]*cofator + Ac[j,:]
      Bc[j] = Bc[i]*cofator + Bc[j]

  return (Ac,Bc)

In [105]:
def calcula_sol_mat_sup(A,B):
  xr = np.zeros([len(A),1],dtype='float')
  idr = len(A)-1
  while idr >= 0:
    z = idr
    soma = 0
    while z < len(A)-1:
      soma = soma+A[idr,z]*xr[z]
      z = z + 1
    xr[idr] = (B[idr]-soma)/A[idr,idr]
    idr = idr - 1
  return(xr)

In [106]:
I = np.eye(3)
B1 = I [:,0]
B2 = I [:,1]
B3 = I [:,2]


In [119]:
[Ac1,Bc1] = elimina_gauss_piv(A,B1)
x1 = calcula_sol_mat_sup(Ac1,Bc1)
[Ac2,Bc2] = elimina_gauss_piv(A,B2)
x2 = calcula_sol_mat_sup(Ac2,Bc2)
[Ac3,Bc3] = elimina_gauss_piv(A,B3)
x3 = calcula_sol_mat_sup(Ac3,Bc3)

[[ 2.   1.  -1. ]
 [ 0.   2.5 -0.5]
 [ 0.   0.  -0.2]]
[ 1.   0.5 -0.8]


In [117]:
sol = np.zeros([ordem,ordem], dtype = 'float')
sol = np.concatenate((x1,x2,x3),axis=1)
print(sol)

[[ 0.  -0.2  0.4]
 [ 0.   0.4  0.2]
 [-5.   3.   4. ]]


In [111]:
print(np.linalg.inv (A))

[[-2.  1.  2.]
 [-1.  1.  1.]
 [-5.  3.  4.]]
