<a href="https://colab.research.google.com/github/Guilhermeslsand/Python/blob/main/Pr%C3%A1tica_Sistemas_Equa%C3%A7%C3%B5es_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import math
import matplotlib.pyplot as plt

In [3]:
ordem = int(input(("Fornecer a ordem do Sistema de Equações")))
A = np.zeros([ordem,ordem], dtype = 'float')
B = np.zeros([ordem,1],dtype='float')


Fornecer a ordem do Sistema de Equações4


In [15]:
for i in range(0,ordem):
  for j in range(0,ordem):
    A[i,j] = float(input(f'Elemento da possição ({i+1},{j+1}) da matriz A:'))
for i in range(0,ordem):
  B[i,0] = float(input(f'Elemento da possição ({i+1},1) da matriz B:'))

Elemento da possição (1,1) da matriz A:2
Elemento da possição (1,2) da matriz A:0
Elemento da possição (1,3) da matriz A:0
Elemento da possição (1,4) da matriz A:0
Elemento da possição (2,1) da matriz A:3
Elemento da possição (2,2) da matriz A:5
Elemento da possição (2,3) da matriz A:0
Elemento da possição (2,4) da matriz A:0
Elemento da possição (3,1) da matriz A:1
Elemento da possição (3,2) da matriz A:-6
Elemento da possição (3,3) da matriz A:8
Elemento da possição (3,4) da matriz A:0
Elemento da possição (4,1) da matriz A:-1
Elemento da possição (4,2) da matriz A:4
Elemento da possição (4,3) da matriz A:-3
Elemento da possição (4,4) da matriz A:9
Elemento da possição (1,1) da matriz B:4
Elemento da possição (2,1) da matriz B:1
Elemento da possição (3,1) da matriz B:48
Elemento da possição (4,1) da matriz B:6


In [18]:
def calcula_sol_mat(A,B):
  xr = np.zeros([len(A),1],dtype='float')
  idr = 0
  while idr <len(A):
    z = 0
    soma = 0
    while z < idr:
      soma = soma+A[idr,z]*xr[z]
      z = z + 1
    xr[idr] = (B[idr]-soma)/A[idr,idr]
    idr = idr + 1
  return(xr)

In [20]:
print(calcula_sol_mat(A,B))

[[ 2.]
 [-1.]
 [ 5.]
 [ 3.]]
[[ 2.  0.  0.  0.]
 [ 3.  5.  0.  0.]
 [ 1. -6.  8.  0.]
 [-1.  4. -3.  9.]]


In [ ]:
for i in range(0,ordem):
  for j in range(0,ordem):
    A[i,j] = float(input(f'Elemento da possição ({i+1},{j+1}) da matriz A:'))
for i in range(0,ordem):
  B[i,0] = float(input(f'Elemento da possição ({i+1},1) da matriz B:'))

In [29]:
def calcula_sol_mat_sup(A,B):
  xr = np.zeros([len(A),1],dtype='float')
  idr = len(A)-1
  while idr >= 0:
    z = idr
    soma = 0
    while z < len(A)-1:
      soma = soma+A[idr,z]*xr[z]
      z = z + 1
    xr[idr] = (B[idr]-soma)/A[idr,idr]
    idr = idr - 1
  return(xr)

In [ ]:
print(calcula_sol_mat_sup(A,B))

In [33]:
def elimina_gauss(A,B):
  Ac= np.copy(A)
  Bc = np.copy(B)
  for i in range(0,len(A)-1):
    pivo = Ac[i,i]
    for j in (i+1,len(A)):
      cofator = (-1)*Ac[j,i]/Ac[i,i]
      Ac[j,:] = Ac[i,:]*cofator + Ac[j:]
      Bc[j] = Bc[i]*cofator + Bc[j]
  return (Ac,Bc)

In [31]:
ordem = 3
for i in range(0,ordem):
  for j in range(0,ordem):
    A[i,j] = float(input(f'Elemento da possição ({i+1},{j+1}) da matriz A:'))
for i in range(0,ordem):
  B[i,0] = float(input(f'Elemento da possição ({i+1},1) da matriz B:'))

Elemento da possição (1,1) da matriz A:1
Elemento da possição (1,2) da matriz A:-3
Elemento da possição (1,3) da matriz A:2
Elemento da possição (2,1) da matriz A:-2
Elemento da possição (2,2) da matriz A:8
Elemento da possição (2,3) da matriz A:-1
Elemento da possição (3,1) da matriz A:4
Elemento da possição (3,2) da matriz A:-6
Elemento da possição (3,3) da matriz A:5
Elemento da possição (1,1) da matriz B:11
Elemento da possição (2,1) da matriz B:-15
Elemento da possição (3,1) da matriz B:29


In [35]:
[At,Bt] = elimina_gauss(A,B)
print(At)
print(Bt)

ValueError: ignored